version: '3.8'

services:
  fastapi:
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - elk
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  # Use service name
      - LOGSTASH_HOST=logstash  # Use service name
      - LOGSTASH_PORT=5959
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  elasticsearch:
    image: elasticsearch:7.16.2
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"  # Increased memory limits
      discovery.type: single-node    
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk

  logstash:
    image: logstash:7.16.2
    restart: always
    volumes:
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf 
    depends_on:
        - elasticsearch
    ports:
      - '5959:5959'
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"  # Increased memory limits    
    networks:
        - elk

  kibana:
    image: kibana:7.16.2
    restart: always       
    ports:
      - '5601:5601'
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
        - elasticsearch  
    networks:
        - elk

volumes:
  elastic_data: {}

networks:
  elk:
